wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1699837344.408059
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.13.10
      8:
      - 5
balance:
  desc: null
  value: true
batch:
  desc: null
  value: 128
cross:
  desc: null
  value: null
data_path:
  desc: null
  value: /home/megh98/datasets
dataset:
  desc: null
  value: CIFAR10
device:
  desc: null
  value: cuda
epochs:
  desc: null
  value: 200
experiment_count:
  desc: null
  value: 0
fraction:
  desc: null
  value: 0.1
gamma:
  desc: null
  value: 0.5
gpu:
  desc: null
  value: null
lr:
  desc: null
  value: 0.1
min_lr:
  desc: null
  value: 0.0001
model:
  desc: null
  value: ResNet9
momentum:
  desc: null
  value: 0.9
nesterov:
  desc: null
  value: true
num_eval:
  desc: null
  value: 10
num_exp:
  desc: null
  value: 5
optimizer:
  desc: null
  value: SGD
print_freq:
  desc: null
  value: 20
resume:
  desc: null
  value: ''
save_path:
  desc: null
  value: ./result
scheduler:
  desc: null
  value: CosineAnnealingLR
seed:
  desc: null
  value: 42707
selection:
  desc: null
  value: Glister
selection_batch:
  desc: null
  value: 128
selection_epochs:
  desc: null
  value: 10
selection_lr:
  desc: null
  value: 0.1
selection_momentum:
  desc: null
  value: 0.9
selection_nesterov:
  desc: null
  value: true
selection_optimizer:
  desc: null
  value: SGD
selection_test_fraction:
  desc: null
  value: 1.0
selection_test_interval:
  desc: null
  value: 1
selection_weight_decay:
  desc: null
  value: 0.0005
step_size:
  desc: null
  value: 50
submodular:
  desc: null
  value: GraphCut
submodular_greedy:
  desc: null
  value: LazyGreedy
test_fraction:
  desc: null
  value: 1.0
test_interval:
  desc: null
  value: 1
train_batch:
  desc: null
  value: 128
uncertainty:
  desc: null
  value: Entropy
weight_decay:
  desc: null
  value: 0.0005
workers:
  desc: null
  value: 10
